### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by mweinelt** [JensTimmerman/ansible-role-vaultwarden#16]
It would be awesome if you could tag a new release, that users could pin, instead of a rolling branch.

**Comment by JensTimmerman** [comment]
I'll do it manually for now, and look into integrating that in a github workflow later, so I'll keep this issue open

**Comment by JensTimmerman** [comment]
@mweinelt  see https://github.com/JensTimmerman/ansible-role-vaultwarden/releases/tag/v0.6.0

**Comment by JensTimmerman** [comment]
would you also want me to push this to galaxy? 
The travis.yml should do this (I got this from the galaxy documentation) but it's not working at the moment, see also #1

**Comment by mweinelt** [comment]
Would be sensible to push it there. Not an expert when it comes to GitHub Actions

**Comment by JensTimmerman** [comment]
new release is available on galaxy now. Had to do it manually now, see https://github.com/ansible/galaxy/issues/2813
