### ISSUE TITLE
0.5 is not on Ansible Galaxy

### ISSUE THREAD

**Issue by mweinelt** [JensTimmerman/ansible-role-vaultwarden#3]
(title says it all)

Thanks for maintaining this role!

**Comment by hevisko** [comment]
:(

**Comment by JensTimmerman** [comment]
I'm sorry for the late reply, github wasn't mailing me, I 've now enabled all activity mails ;)

As you can see I have added a .travis.yml and tried to configure this to auto upload to ansible galaxy,  https://galaxy.ansible.com/docs/contributing/importing.html#import-roles-via-travis-ci

Something there must not be completly right yet, manually imported now.
